### ISSUE TITLE
papers are come

### ISSUE THREAD

**Issue by Yagya1123** [YagyadeepClou/study#7]
i am a student and i want some holidays

**Comment by Yagya1123** [comment]
![screenshot from 2017-05-02 11-24-14](https://user-images.githubusercontent.com/31754093/30999585-ab5e1b68-a4f3-11e7-87ba-c134d1e89105.png)

**Comment by Yagya1123** [comment]
#7

**Comment by YagyadeepClou** [comment]
#7

**Comment by Yagya1123** [comment]
now go
